services:

  ui_with_auth_via_is:
    image: ui_with_auth_via_is
    container_name: ui_with_auth_via_is
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "4200:4200"
    tty: true

networks:
  default:
    name: myLocalNetwork # создана извне: docker network create --driver=bridge myLocalNetwork
    external: true